name: Gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # - name: gitleaks-action
    #   uses: zricethezav/gitleaks-action@master
    - name: customized gitleaks
      uses: sushi2k/gitleaks-action@master
      with:
        extra-args: -o gitleaks.json
    - name: List files in the workspace
      run: |
        ls ${{ github.workspace }}
    - uses: actions/upload-artifact@v2
      with:
        name: gitleaks
        path: gitleaks.json
    
    
      # with:
      #   extra-args: -f sarif -r gitleaks.sarif
    # - name: Upload Test results
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: Gitleaks report
    #     path: ${{github.workspace}}/gitleaks.sarif
